name: Build artifacts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build jar
        run: ./gradlew test assemble
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: android-attestation
          path: |
            build/libs/*jar
